Repository mdflynn/rancid-tomatillos, pull requests merged in 2020-12, with the labels that each got.

#4 Feature/conditional rendering
  src/App/App.js
  src/Movie/Movie.js
  src/Movie/Movie.scss
  src/MovieCard/MovieCard.js
  src/MovieContainer/MovieContainer.js
  src/Nav/Nav.js
  src/Nav/Nav.scss
  src/assets/tomatillo.png
Labels: enhancement

#13 Feature/unit testing
  package-lock.json
  package.json
  src/App/App.js
  src/App/App.test.js
  src/Movie/Movie.js
  src/Movie/Movie.test.js
  src/MovieCard/MovieCard.js
  src/MovieCard/MovieCard.test.js
  src/MovieContainer/MovieContainer.test.js
  src/Nav/Nav-test.js
  src/Nav/Nav.js
  src/Nav/Nav.test.js
  src/callApis.js
Labels: enhancement, feature

#17 Feature/create form
  src/App/App.js
  src/Form/Form.js
  src/Form/Form.scss
  src/Form/Form.test.js
  src/Movie/Movie.scss
  src/MovieCard/MovieCard.scss
  src/Nav/Nav.js
  src/Nav/Nav.scss
  src/assets/NightmarePills-BV2w.ttf
Labels: enhancement, feature

#22 Feature/display video
  package-lock.json
  package.json
  src/App/App.js
  src/App/App.test.js
  src/Form/Form.test.js
  src/Movie/Movie.js
  src/Movie/Movie.test.js
  src/MovieCard/MovieCard.js
  src/MovieCard/MovieCard.test.js
  src/MovieContainer/MovieContainer.test.js
  src/Nav/Nav.js
  src/Nav/Nav.scss
  src/Nav/Nav.test.js
  src/callApis.js
Labels: enhancement, feature

#25 Feature/design movie card
  src/App/App.js
  src/App/App.test.js
  src/Movie/Movie.js
  src/Movie/Movie.scss
  src/Movie/Movie.test.js
  src/assets/001-thumbs-up-hand-symbol.png
  src/assets/002-thumbs-down-silhouette.png
  src/callApis.js
  src/index.scss
Labels: enhancement, feature

#26 Feature/final styling
  package.json
  src/App/App.js
  src/App/App.scss
  src/App/App.test.js
  src/Form/Form.js
  src/Form/Form.scss
  src/Form/Form.test.js
  src/Movie/Movie.js
  src/Movie/Movie.scss
  src/Movie/Movie.test.js
  src/MovieCard/MovieCard.js
  src/MovieCard/MovieCard.scss
  src/MovieCard/MovieCard.test.js
  src/MovieContainer/MovieContainer.js
  src/MovieContainer/MovieContainer.scss
  src/MovieContainer/MovieContainer.test.js
  src/Nav/Nav.js
  src/Nav/Nav.scss
  src/Nav/Nav.test.js
  src/index.js
  src/movieData.js
Labels: enhancement

#30 Compile scss into css
  package-lock.json
  package.json
  src/App/App.css
  src/App/App.css.map
  src/App/App.js
  src/Form/Form.css
  src/Form/Form.css.map
  src/Movie/Movie.css
  src/Movie/Movie.css.map
  src/MovieCard/MovieCard.css
  src/MovieCard/MovieCard.css.map
  src/MovieContainer/MovieContainer.css
  src/MovieContainer/MovieContainer.css.map
  src/Nav/Nav.css
  src/Nav/Nav.css.map
  src/index.css
  src/index.css.map
Labels: documentation
